####### TYPES ######~

TOKEN_ID = 'ID'
TOKEN_INT = 'INT'
TOKEN_FLOAT = 'FLOAT'


####### OPERATORS #######

TOKEN_PLUS = 'PLUS'
TOKEN_MINUS = 'MINUS'
TOKEN_MULTIPLY = 'MULTIPLY'
TOKEN_DIVIDE = 'DIVIDE'
TOKEN_EQUALS = 'EQUALS'


####### MARKERS #######

TOKEN_COLON = 'COLON'
TOKEN_RARROW = 'RARROW'
TOKEN_LPAREN = 'LPAREN'
TOKEN_RPAREN = 'RPAREN'
TOKEN_LBRACE = 'LBRACE'
TOKEN_RBRACE = 'RBRACE'
TOKEN_EOF = 'EOF'
